### ISSUE TITLE
Q: shouldn't `callbackUrl` in the examples be in env vars also?

### ISSUE THREAD

**Issue by tbntdima** [Nekonyx/next-auth-steam#22]
Hi, thanks for your work!
Noticed a small thing, it's basically in the issue title.

**Comment by Nekonyx** [comment]
Hi.
Because it depends on the developer's preference, and there is no universally accepted recommendation about it. Unlike secrets, which in the examples are properly stored in .env.

Personally, I use:
```ts
callbackUrl: `${process.env.APP_URL}/api/auth/callback`
```
Since I keep a link to my application in environment variables, so I can use it in many other places.

**Comment by tbntdima** [comment]
Makes sense, thanks for the reply.
